import { NavBar } from '../../framework/components/header/header'
import type { Metadata } from 'next'
import '../globals.css'
import { Inter } from 'next/font/google'
import { Footer } from '@/framework/components/foolter/footer';



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body >
        <header>

        <NavBar />
        </header>
        {children}
        <Footer />
        </body>
    </html>
  )
}
