import Sidebar from "@/framework/components/side-bar/side-bar";
import type { Metadata } from "next";
import "./styles.scss";
import "src/app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PrivateLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body>

    <section className="privates-container">
      <Sidebar />
      <div className="lateral">
      </div>
      <main>{children}</main>
        
    </section>
      </body>
    </html>
  );
}
