import Sidebar from "@/framework/components/side-bar/side-bar";
import "../globals.css";
import "./styles.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      <div className="layout-sobre">
        <nav className="layout-sobre__nav">
          <Sidebar />
        </nav>
        {children}
      </div>
    </section>
  );
}
